# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Search Party Developer Center
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Developer Support site for Search Party
baseurl: "/searchparty-dev-site" # the subpath of your site, e.g. /blog
url: "http://thesearchparty.github.io/" # the base hostname & protocol for your site
twitter_username: TheSearchParty
github_username:  thesearchparty

# Build settings
markdown: kramdown
timezone: Australia/Sydney